version: '3.8'

# Development overrides for hot-reload and debugging
services:
  api:
    build:
      target: dependencies
    command: npm run dev --workspace=apps/api
    environment:
      NODE_ENV: development
      DEBUG: '*'
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./apps/api/tsconfig.json:/app/apps/api/tsconfig.json
      - ./packages:/app/packages
      - ./tsconfig.json:/app/tsconfig.json

  web:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.web.dev
    ports:
      - "4200:4200"
    volumes:
      - ./apps/web/src:/app/apps/web/src
      - ./apps/web/angular.json:/app/apps/web/angular.json
      - ./apps/web/tsconfig.json:/app/apps/web/tsconfig.json
      - ./apps/web/tsconfig.app.json:/app/apps/web/tsconfig.app.json
      - ./packages:/app/packages
    environment:
      NODE_ENV: development