name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the sections below to help us understand and fix the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the troubleshooting guide
          required: true
        - label: I am using the latest version of NodeAngularFullStack
          required: false

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Affected
      description: Which part of the application is affected?
      options:
        - Frontend (Angular)
        - Backend (Express.js)
        - Database (PostgreSQL)
        - Authentication
        - Multi-tenancy
        - Docker/Infrastructure
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue that doesn't affect functionality
        - Medium - Issue affects functionality but has workaround
        - High - Issue affects core functionality
        - Critical - Application is unusable or data loss occurs
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide environment details
      value: |
        - OS: [e.g. macOS 13.0, Windows 11, Ubuntu 22.04]
        - Node.js version: [e.g. 18.19.0]
        - npm version: [e.g. 9.0.0]
        - Browser: [e.g. Chrome 118, Firefox 119, Safari 17]
        - Docker version: [e.g. 24.0.0]
        - Project version: [e.g. 1.2.3]
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      placeholder: |
        Paste error logs here...
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop screenshots here or provide URLs

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be relevant...

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: If you have ideas on how to fix this, please describe them
      placeholder: Your ideas for fixing the issue...

  - type: checkboxes
    id: contributing
    attributes:
      label: Contributing
      options:
        - label: I am willing to submit a pull request to fix this bug
          required: false