blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/your-org/NodeAngularFullStack/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://docs.nodeangularfullstack.com
    about: Check our comprehensive documentation before opening an issue
  - name: 🚀 Getting Started Guide
    url: https://docs.nodeangularfullstack.com/getting-started
    about: New to the project? Start here with our setup guide
  - name: 🔧 Troubleshooting Guide
    url: https://docs.nodeangularfullstack.com/troubleshooting
    about: Common issues and solutions