name: ✨ Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the sections below to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have checked the roadmap to see if this feature is already planned
          required: true
        - label: This feature aligns with the project's goals and scope
          required: false

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see added
      placeholder: Describe the feature you want...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What use case does it address?
      placeholder: |
        As a [type of user], I want [feature] so that [benefit/goal].

        Currently, [describe the problem or limitation]...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your preferred solution in detail
      placeholder: |
        I propose [detailed description of the solution]...

        This would work by [explain the approach]...
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions you've considered
      placeholder: |
        Alternative 1: [description]
        Alternative 2: [description]

        Why the proposed solution is better: [reasoning]

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New API endpoint
        - Frontend component
        - Authentication enhancement
        - Multi-tenancy improvement
        - Developer tooling
        - Documentation improvement
        - Performance optimization
        - Security enhancement
        - Testing improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my project
    validations:
      required: true

  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation Details
      description: If you have technical implementation ideas, please share them
      placeholder: |
        Technical approach:
        - [Step 1]
        - [Step 2]
        - [Step 3]

        Files that might need changes:
        - [File 1]
        - [File 2]

        New dependencies (if any):
        - [Dependency 1]
        - [Dependency 2]

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define what success looks like for this feature
      placeholder: |
        This feature is complete when:
        - [ ] [Criterion 1]
        - [ ] [Criterion 2]
        - [ ] [Criterion 3]
        - [ ] Documentation is updated
        - [ ] Tests are added

  - type: textarea
    id: examples
    attributes:
      label: Examples and Mockups
      description: Provide examples, mockups, or references to similar implementations
      placeholder: |
        Example usage:
        ```typescript
        // Code example of how the feature would be used
        ```

        Similar implementations:
        - [Project/Library that has similar feature]

        Mockups or wireframes:
        - [Attach images or provide links]

  - type: dropdown
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - No breaking changes
        - Minor breaking changes (with migration path)
        - Major breaking changes (requires new major version)
        - Unsure
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: |
        Additional information:
        - [Context 1]
        - [Context 2]

        Related issues or PRs:
        - #123
        - #456

  - type: checkboxes
    id: contributing
    attributes:
      label: Contributing
      options:
        - label: I am willing to submit a pull request to implement this feature
          required: false
        - label: I am willing to help with testing this feature
          required: false
        - label: I am willing to help with documentation for this feature
          required: false