# Simple Digital Ocean App Platform Configuration
# For initial deployment without custom domains

name: nodeangularfullstack
region: nyc1

# Database configuration
databases:
  - name: postgres-db
    engine: PG
    production: false  # Set to true for production
    version: "15"
    size: basic
    num_nodes: 1
    db_name: nodeangularfullstack
    db_user: app_user

# Services configuration
services:
  # Backend API Service
  - name: api
    source_dir: /
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true
    dockerfile_path: infrastructure/docker/Dockerfile.api

    # Basic resource allocation
    instance_count: 1
    instance_size_slug: basic-xxs

    # Health check
    health_check:
      http_path: /api/v1/health/liveness
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    # HTTP configuration
    http_port: 3000

    # Essential environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        type: SECRET
        value: ${postgres-db.DATABASE_URL}
      - key: JWT_SECRET
        type: SECRET
        value: your-jwt-secret-here
      - key: JWT_REFRESH_SECRET
        type: SECRET
        value: your-jwt-refresh-secret-here
      - key: CORS_ORIGIN
        value: "*"  # Configure properly for production

# Static sites configuration
static_sites:
  # Frontend Angular Application
  - name: web
    source_dir: /
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true
    dockerfile_path: infrastructure/docker/Dockerfile.web

    # Build configuration
    build_command: npm run build:web
    output_dir: apps/web/dist/web/browser

    # Environment variables
    envs:
      - key: NODE_ENV
        value: production

    # Routes to API
    routes:
      - path: /api
        preserve_path_prefix: true
        component_name: api

    # SPA routing
    error_document: index.html

# Basic alerts
alerts:
  - rule: CPU_UTILIZATION
    threshold: 90
    operator: GREATER_THAN
    window: FIVE_MINUTES